# The following workflow executes a diamond workflow
#
#   A
#  / \
# B   C
#  \ /
#   D
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
  annotations:
    frog: foobar
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        depends: "B && C"
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: ghcr.io/equinix-labs/otel-cli:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          export TRACEPARENT="${ARGO_OTEL_traceparent}"
          export OTEL_EXPORTER_OTLP_PROTOCOL=grpc
          export
          /otel-cli exec --name sleep sleep 3
          /otel-cli exec --name party sleep 5
          /otel-cli exec --name clean sleep 5
